-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 14:49:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sesion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sesion` (
  `idsesion` INT NOT NULL AUTO_INCREMENT,
  `ejecucion` INT NULL,
  `descanso` INT NULL,
  `pomodoro1` INT NULL,
  `pomodoro2` INT NULL,
  `pomodoro3` INT NULL,
  `pomodoro4` INT NULL,
  `descanso1` INT NULL,
  `descanso2` INT NULL,
  `descanso3` INT NULL,
  `descanso4` INT NULL,
  `fecha` DATETIME NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idsesion`),
  INDEX `fk_sesion_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_sesion_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$

USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`sesion_BEFORE_INSERT` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`sesion_BEFORE_INSERT` BEFORE INSERT ON `sesion` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
