-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 14:49:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema arqui2proy1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `arqui2proy1` ;

-- -----------------------------------------------------
-- Schema arqui2proy1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `arqui2proy1` DEFAULT CHARACTER SET utf8 ;
USE `arqui2proy1` ;

-- -----------------------------------------------------
-- Table `arqui2proy1`.`sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arqui2proy1`.`sesion` ;

CREATE TABLE IF NOT EXISTS `arqui2proy1`.`sesion` (
  `idsesion` INT NOT NULL AUTO_INCREMENT,
  `ejecucion` INT NULL,
  `descanso` INT NULL,
  `pomodoro1` INT NULL,
  `pomodoro2` INT NULL,
  `pomodoro3` INT NULL,
  `pomodoro4` INT NULL,
  `descanso1` INT NULL,
  `descanso2` INT NULL,
  `descanso3` INT NULL,
  `descanso4` INT NULL,
  `fecha` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idsesion`),
  INDEX `fk_sesion_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_sesion_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `arqui2proy1`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arqui2proy1`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arqui2proy1`.`usuario` ;

CREATE TABLE IF NOT EXISTS `arqui2proy1`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;

USE `arqui2proy1`;

DELIMITER $$

USE `arqui2proy1`$$
DROP TRIGGER IF EXISTS `arqui2proy1`.`sesion_BEFORE_INSERT` $$
USE `arqui2proy1`$$
CREATE DEFINER = CURRENT_USER TRIGGER `arqui2proy1`.`sesion_BEFORE_INSERT` BEFORE INSERT ON `sesion` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO usuario (nombre) VALUES ('Juan');
INSERT INTO usuario (nombre) VALUES ('Maria');
INSERT INTO usuario (nombre) VALUES ('Pedro');
INSERT INTO sesion (ejecucion, descanso, pomodoro1, pomodoro2, pomodoro3, pomodoro4, descanso1, descanso2, descanso3, descanso4, usuario_idusuario) VALUES 
(FLOOR(RAND() * 21) + 25, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, 1),
(FLOOR(RAND() * 21) + 25, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, 1),
(FLOOR(RAND() * 21) + 25, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, 1);

INSERT INTO sesion (ejecucion, descanso, pomodoro1, pomodoro2, pomodoro3, pomodoro4, descanso1, descanso2, descanso3, descanso4, usuario_idusuario) VALUES 
(FLOOR(RAND() * 21) + 25, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, 2),
(FLOOR(RAND() * 21) + 25, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, 2),
(FLOOR(RAND() * 21) + 25, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 15) + 1, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, FLOOR(RAND() * 16) + 5, 2);