use proy2;
CREATE TABLE IF NOT EXISTS `proy2`.`datos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `state_bomba` INT NULL,
  `time_irrigation` INT NULL,
  `temp_externa` INT NULL,
  `temp_interna` INT NULL,
  `water_percent` INT NULL,
  `humidity` INT NULL,
  PRIMARY KEY (`id`)
);

select * from datos;

INSERT INTO `proy2`.`datos`
(`fecha`, `state_bomba`, `time_irrigation`, `temp_externa`, `temp_interna`, `water_percent`, `humidity`)
VALUES
(DATE_SUB(NOW(), INTERVAL 1 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 2 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 3 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 4 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 5 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 1 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 2 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 3 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 4 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 5 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 1 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 2 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 3 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 4 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 5 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 1 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 2 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 3 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 4 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 5 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 1 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 2 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 3 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 4 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 5 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100))
,(DATE_SUB(NOW(), INTERVAL 1 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 2 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 3 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 4 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 5 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100))
,(DATE_SUB(NOW(), INTERVAL 1 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 2 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 3 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 4 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100)),
(DATE_SUB(NOW(), INTERVAL 5 DAY), FLOOR(RAND() * 2), FLOOR(RAND() * 100), FLOOR(RAND() * 50), FLOOR(RAND() * 50), FLOOR(RAND() * 100), FLOOR(RAND() * 100))
;

select * from datos;